### ISSUE TITLE
[Feature 2] UserQueryConstraint-Filter

### ISSUE THREAD

**Issue by stevolopolis** [CSC207-2022F-UofT/course-project-team-java-help#20]

**Comment by Jacob4649** [comment]
This will need to be changed from our CRC model. Predicates will not work well with a database. We probably need to setup the `UserQueryConstraint` class so that method calls can be chained, with each method call adding a new constraint of some kind on a field. The interaction between `UserQueryConstraint` objects and the database should be implemented by the implementation of the `IUserStore` interface, rather than in some central location.
